//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BooksInKart = new HashSet<BooksInKart>();
            this.OrderByItem = new HashSet<OrderByItem>();
        }
    
        public int BookID { get; set; }
        public string AuthorName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string BookDescription { get; set; }
        public Nullable<int> BookStatusId { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string BookName { get; set; }
        public string BookURL { get; set; }
    
        public virtual BookStatus BookStatus { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<BooksInKart> BooksInKart { get; set; }
        public virtual ICollection<OrderByItem> OrderByItem { get; set; }
    }
}
