//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksInKart
    {
        public int BooksInKart1 { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> kartTotal { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<bool> StatusId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Users Users { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
