//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookDBContext : DbContext
    {
        public BookDBContext()
            : base("name=BookDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admins> Admins { get; set; }
        public DbSet<Book> Book { get; set; }
        public DbSet<BooksInKart> BooksInKart { get; set; }
        public DbSet<BookStatus> BookStatus { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<OrderByItem> OrderByItem { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<PaymentType> PaymentType { get; set; }
        public DbSet<ShippingAddress> ShippingAddress { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<CustomerMessage> CustomerMessage { get; set; }
    }
}
