//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.BooksInKart = new HashSet<BooksInKart>();
            this.Orders = new HashSet<Orders>();
            this.ShippingAddress = new HashSet<ShippingAddress>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AccountStatus { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<BooksInKart> BooksInKart { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<ShippingAddress> ShippingAddress { get; set; }
    }
}
